[package]
name = "betty-mcp-component"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.47"
wasmcloud-component = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-mcp-schema = "=0.9.5"

waki = "0.5.1"